import { AppLayout } from '../components/AppLayout';
import '../public/styles/global.scss';
import './global.css';

export const metadata = {
  title: 'Welcome to customer-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
