services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    image: ghcr.io/xafpay/wallet_api:latest
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - '5000:5000'

  postgres:
    image: postgres:alpine
    container_name: xafpay_api_db
    env_file:
      - .env
    volumes:
      - xafpay_api_pgdata:/var/lib/postgresql/data # Persistent storage for PostgreSQL
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    # container_name: xafpay_api_cache
    ports:
      - '6379:6379'
 
  app:
    build:
      dockerfile: Dockerfile.app
      context: .
    restart: unless-stopped
    image: ghcr.io/xafpay/wallet_fe:latest
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - '3000:3000'

volumes:
  xafpay_api_pgdata:
    driver: local
