# syntax=docker.io/docker/dockerfile:1
FROM node:23-alpine AS deps

# #set the working directory
WORKDIR /app

COPY package*.json ./

# clean install dependecies
RUN --mount=type=cache,target=/app/node_modules \ 
    npm ci --verbose

FROM deps AS builder
WORKDIR /app

# COPY workspace configs
COPY package*.json ./
COPY ./tsconfig.base.json ./
COPY ./nx.json ./

COPY --from=deps /app/node_modules ./node_modules
COPY ./apps/wallet-api ./apps/wallet-api
COPY ./prisma ./prisma

# Generate prisma client
RUN npx prisma generate

# Build backend app
RUN npx nx run wallet-api:build:production

FROM builder AS runner
WORKDIR /app

# Use a non-root user for securityRUN addgroup -S nodejs && adduser -S nestjs -G nodejs
USER nestjs

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist/apps/wallet-api ./dist
COPY --from=builder /app/prisma ./dist/prisma

# # expose port 5000 to outer environment
EXPOSE 5000

# run app
CMD prisma migrate deploy && node /app/dist/main.js
