services:
  xafpay_api:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    restart: always
    # image: node:20-alpine3.17 # Use the Node.js image, or build from your own Dockerfile
    # container_name: xafpay_api
    # working_dir: /app
    # volumes:
    #   - .:/app
    #   - /app/node_modules # Ensures node_modules are accessible inside the container
    # # command: sh -c "npm install --force && npx nx serve wallet-api"
    # command: sh -c "npm install --force && npx prisma generate && npm run migrate-reset && npx nx serve wallet-api"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '5000:5000'

  postgres:
    image: postgres:alpine
    container_name: xafpay_api_db
    env_file:
      - .env
    volumes:
      - xafpay_api_pgdata:/var/lib/postgresql/data # Persistent storage for PostgreSQL
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    # container_name: xafpay_api_cache
    ports:
      - '6379:6379'
  app:
    build:
      dockerfile: ./Dockerfile.app
      context: .
    restart: always
    depends_on:
      - xafpay_api
    ports:
      - '3000:3000'

volumes:
  xafpay_api_pgdata:
    driver: local
