# syntax=docker.io/docker/dockerfile:1
FROM node:23-alpine AS base

LABEL maintainer="Marco Kuidja <kuidjamarco@gmail.com>"
LABEL org.opencontainers.image.description="NestJs backend for the XafPay Wallet"

# Installing openssl for prisma
RUN apk update \
    && apk add --no-cache openssl

# #set the working directory
WORKDIR /app

# Install dependencies
RUN --mount=type=bind,src=package.json,target=/app/package.json \
    --mount=type=bind,src=package-lock.json,target=/app/package-lock.json \
    --mount=type=cache,target=/app/node_modules \
    npm ci

FROM base AS deps
# clean install dependecies
RUN --mount=type=cache,target=/app/node_modules \ 
    --mount=type=bind,src=package.json,target=/app/package.json \ 
    --mount=type=bind,src=package-lock.json,target=/app/package-lock.json \ 
    npm ci

# Generate prisma client and build backend app
RUN --mount=type=cache,target=/app/node_modules \
    npx prisma generate \
    && NX_CLOUD=0 npx nx run wallet-api:build:production \
    && cp -R /app/dist/apps/wallet-api ./final-dist \
    # Install only wallet-api production dependencies
    && npm ci --omit=dev --prefix dist/apps/wallet-api/

FROM base AS runner

ENV NODE_ENV=production
ENV PORT=5000

# Use a non-root user for security
RUN addgroup -S -g 1001 nodejs && adduser -S nestjs -G nodejs -u 1001

# Copy necessary files from builder stage
COPY --from=builder --chown=nestjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nestjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /app/final-dist ./

USER nestjs

# Expose port 5000 to outer environment
EXPOSE 5000

# Run app
CMD npx prisma migrate deploy && node /app/main.js
