version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - '3000:5000'

  postgres:
    image: postgres:alpine
    container_name: xafpay_api_db
    env_file:
      - .env
    volumes:
      - xafpay_api_pgdata:/var/lib/postgresql/data # Persistent storage for PostgreSQL
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    container_name: xafpay_api_cache
    ports:
      - '6379:6379'
  # app:
  #   build:
  #     dockerfile: ./Dockerfile.app
  #     context: .
  #   restart: always
  #   environment:
  #     - NX_NODE_ENV=production
  #   ports:
  #     - '3000:3000'

volumes:
  xafpay_api_pgdata:
    driver: local
