export const constants = {
  WEBHOOK_QUEUE: 'webhooks_processors_queue',
  CYBRID_SCOPES: [
    'banks:read',
    'banks:write',
    'bank_applications:execute',
    'accounts:read',
    'accounts:execute',
    'counterparties:read',
    'counterparties:write',
    'counterparties:execute',
    'customers:read',
    'customers:write',
    'customers:execute',
    'prices:read',
    'quotes:execute',
    'quotes:read',
    'trades:execute',
    'trades:read',
    'transfers:execute',
    'transfers:read',
    'external_bank_accounts:read',
    'external_bank_accounts:write',
    'external_bank_accounts:execute',
    'external_wallets:read',
    'external_wallets:execute',
    'workflows:read',
    'workflows:execute',
    'deposit_addresses:read',
    'deposit_addresses:execute',
    'deposit_bank_accounts:read',
    'deposit_bank_accounts:execute',
    'invoices:read',
    'invoices:write',
    'invoices:execute',
    'identity_verifications:read',
    'identity_verifications:write',
    'identity_verifications:execute',
  ],
  CYBRID_IDENTITY_VERIFICATION_EVENTS: 'cybrid_identity_verification_events',
  CYBRID_TRANSFER_EVENTS: 'cybrid_transfer_events',
  CYBRID_TRADE_EVENTS: 'cybrid_trade_events',
  PAWAPAY_PAYOUT_EVENTS: 'pawapay_payout_events',
  SUPPORTED_TRADE_SYMBOL: 'USDC_SOL-USD',
  UNSCHEDULED_TRASACTION: 'waiting',
};
