export const cybridConstants = {
  QUEUE: 'CYBRID_QUEUE',
  SCOPE: [
    // 'banks:read',
    // 'banks:write',
    // 'bank_applications:execute',
    'accounts:read',
    'accounts:execute',
    // 'counterparties:read',
    // 'counterparties:write',
    // 'counterparties:execute',
    'customers:read',
    'customers:write',
    'customers:execute',
    // 'prices:read',
    // 'quotes:execute',
    // 'quotes:read',
    // 'trades:execute',
    // 'trades:read',
    // 'transfers:execute',
    // 'transfers:read',
    // 'external_bank_accounts:read',
    // 'external_bank_accounts:write',
    // 'external_bank_accounts:execute',
    // 'external_wallets:read',
    // 'external_wallets:execute',
    // 'workflows:read',
    // 'workflows:execute',
    // 'deposit_addresses:read',
    // 'deposit_addresses:execute',
    // 'deposit_bank_accounts:read',
    // 'deposit_bank_accounts:execute',
    // 'invoices:read',
    // 'invoices:write',
    // 'invoices:execute',
    'identity_verifications:read',
    'identity_verifications:write',
    'identity_verifications:execute',
  ].join(' '),
};
