import { InjectQueue, Process, Processor } from '@nestjs/bull';
import { Logger, NotImplementedException } from '@nestjs/common';
import { PrismaPromise } from '@prisma/client';
import { Job, Queue } from 'bull';
import { constants } from '../../../constants';
import { CybridService } from '../../../cybrid/cybrid.service';
import { validatePhoneNumber } from '../../../helpers/utils';
import { generatePayoutReceiptEmail } from '../../../mailer/emails/payout-email';
import {
  generateTransactionReceiptEmail,
  TransactionReceipt,
} from '../../../mailer/emails/transaction-email';
import { MailerService } from '../../../mailer/mailer.service';
import { PrismaService } from '../../../prisma/prisma.service';
import { InitiatePayoutPayload } from '../../../types/momo';
import { PawapayPayoutEntity } from '../../../types/pawapay';
import { PawapayPayoutStatus } from '../../../types/pawapay/enum';
import { CybridSubscriptionEventObjectDto } from '../dtos/cybrid-subscription.dto';
import { parseEventObject } from '../helpers/event-parser';
import { PeexService } from '../../../peex/peex.service';

@Processor(constants.WEBHOOK_QUEUE)
export class TransactionsProcessor {
  private readonly logger = new Logger(TransactionsProcessor.name);

  constructor(
    private readonly peexService: PeexService,
    private readonly cybridService: CybridService,
    private readonly mailerService: MailerService,
    private readonly prismaService: PrismaService,
    @InjectQueue(constants.WEBHOOK_QUEUE) private readonly webhooksQueue: Queue
  ) {}

  @Process(constants.CYBRID_TRANSFER_EVENTS)
  async handle(job: Job<CybridSubscriptionEventObjectDto>) {
    const { event_type: eventType, guid } = job.data;
    this.logger.log(
      `Processing (event: ${eventType}, Guid: ${guid}) from cybrid...`
    );

    const parsedObject = await parseEventObject(job.data, {
      logger: this.logger,
      prisma: this.prismaService,
    });
    if (!parsedObject) {
      return;
    }

    const {
      customerGuid,
      transactionGuid,
      transactionStatus,
      transaction: cybridTransaction,
    } = parsedObject;

    const transfer = await this.cybridService.getTransfer(
      customerGuid,
      transactionGuid
    );

    const updateOperations: PrismaPromise<unknown>[] = [];

    const supportedTransfeTypes = [
      'crypto',
      'book',
      'funding',
      'instant_funding',
    ];
    if (!supportedTransfeTypes.includes(transfer.transfer_type ?? '')) {
      throw new NotImplementedException(
        `${transfer.transfer_type} transfers not supported yet!`
      );
    }

    if (transfer.transfer_type?.includes('funding')) {
      // Insant funding is done with usd account
      const fiatAccount = await this.cybridService.getAccount(
        customerGuid,
        transfer.destination_account?.guid ?? ''
      );

      updateOperations.push(
        this.prismaService.cybridAccount.update({
          data: {
            // Convert cents to USD
            balance: (fiatAccount.platform_available as number) / 100,
          },
          where: { cybrid_account_guid: fiatAccount.guid },
        })
      );
    } else if (
      transfer.transfer_type === 'book' &&
      cybridTransaction.transaction_type === 'REMITTANCE' &&
      transactionStatus === 'COMPLETED'
    ) {
      // Book transfer (actual remittance) is done with usdc_sol account
      const cryptoAccount = await this.cybridService.getAccount(
        customerGuid,
        transfer.source_account?.guid ?? ''
      );
      updateOperations.push(
        this.prismaService.cybridAccount.update({
          data: {
            // Convert lamports to SOL
            balance: (cryptoAccount.platform_available as number) / 1e6,
          },
          where: { cybrid_account_guid: cryptoAccount.guid },
        })
      );

      // Sending remittance settlement email
      const { person, cybridCounterparty } = await this.sendReceiptEmail(
        cybridTransaction.cybrid_transaction_guid
      );

      const amountReceived =
        cybridTransaction.initial_currency_amount *
        (cybridTransaction.conversion_rate as number);
      const phoneNumber = cybridCounterparty?.phone_number;
      const initiatePayoutPayload: InitiatePayoutPayload = {
        amount: amountReceived,
        customerEmail: person.email,
        transactionId: cybridTransaction.transaction_id,
        receipientPhonenumber: phoneNumber?.includes('237')
          ? phoneNumber
          : `237${phoneNumber}`,
        callbackUrl: `${process.env.API_BASE_URL}/webhooks/payout-callback`,
      };

      await this.initiatePayout(initiatePayoutPayload);
    } else if (
      transfer.transfer_type === 'crypto' &&
      transactionStatus === 'COMPLETED'
    ) {
      // Setteling platform crypto generated by book transfers
      updateOperations.push(
        this.prismaService.cybridTransaction.updateMany({
          data: { settled_at: new Date(), status: transactionStatus },
          where: { cybrid_transfer_settlement_guid: transactionGuid },
        })
      );
    }

    if (transfer.transfer_type !== 'crypto') {
      updateOperations.push(
        this.prismaService.cybridTransaction.update({
          data:
            transactionStatus === 'COMPLETED'
              ? { settled_at: new Date(), status: transactionStatus }
              : { status: transactionStatus },
          where: { cybrid_transaction_guid: transactionGuid },
        })
      );
    }

    // execute prisma transaction against database
    await this.prismaService.$transaction(updateOperations);

    this.logger.log(
      `Successfully processed (event: ${eventType}, Guid: ${guid}) from cybrid.`
    );
  }

  @Process(constants.PAWAPAY_PAYOUT_EVENTS)
  async handlePawapayPayoutEvents(job: Job<PawapayPayoutEntity>) {
    const { payoutId, status, amount } = job.data;

    let transaction = await this.prismaService.cybridTransaction.findFirst({
      where: { pawapay_payout_id: payoutId, settled_at: null },
    });
    if (!transaction) {
      this.logger.error(
        `No transaction record was found for payout Id: ${payoutId}!`
      );
      return;
    }

    if (
      transaction.status === 'COMPLETED' &&
      status === PawapayPayoutStatus.ACCEPTED
    ) {
      transaction = await this.prismaService.cybridTransaction.update({
        data: { settled_at: new Date() },
        where: { cybrid_transaction_id: transaction.cybrid_transaction_id },
      });

      // Sending payout receipt email
      await this.sendReceiptEmail(
        transaction.cybrid_transaction_guid,
        new Date(),
        Number(amount)
      );
    }
  }

  private async sendReceiptEmail(
    transactionGuidOrId: string,
    payoutAt?: Date,
    amountReceived?: number
  ) {
    const {
      InitiatedBy: { Person: person },
      ReceiverPayoutInfo: cybridCounterparty,
      ...cybridTransaction
    } = await this.prismaService.cybridTransaction.findFirstOrThrow({
      include: {
        ReceiverPayoutInfo: true,
        InitiatedBy: { select: { Person: true } },
      },
      where: {
        OR: [
          { transaction_id: transactionGuidOrId },
          { cybrid_transaction_guid: transactionGuidOrId },
        ],
      },
    });

    const transactionId = cybridTransaction.transaction_id;
    const initiatedAt = new Date(cybridTransaction.initiated_at);
    const recipientPhoneNumber = cybridCounterparty?.phone_number;
    const mobileMoneyPartner = recipientPhoneNumber
      ? validatePhoneNumber(recipientPhoneNumber) === 0
        ? 'Mobile Money'
        : 'Orange Money'
      : 'N/A';

    const receiptData: TransactionReceipt = {
      transactionId,
      initiatedAt: initiatedAt.toString(),
      customerName: `${person.first_name} ${person.last_name}`,
      receiptUrl: `/remittance/${cybridTransaction.cybrid_transaction_id}`,
      recipientName: cybridCounterparty?.fullname ?? 'N/A',
      recipientPhoneNumber: `${recipientPhoneNumber} (${mobileMoneyPartner} Cameroon)`,
      amountSent: `${cybridTransaction.initial_currency_amount} ${cybridTransaction.initial_currency}`,
    };

    await this.mailerService.sendMessage({
      to: person.email,
      subject: payoutAt
        ? `Payout Receipt (${transactionId})`
        : `Transaction Receipt (${transactionId})`,
      html: amountReceived
        ? generatePayoutReceiptEmail({
            ...receiptData,
            amountReceived: `${amountReceived} XAF`,
            payoutAt: cybridTransaction.payout_at?.toString() ?? `N/A`,
          })
        : generateTransactionReceiptEmail(receiptData),
    });

    return { person, cybridCounterparty };
  }

  private async initiatePayout({
    transactionId,
    receipientPhonenumber,
    amount,
  }: InitiatePayoutPayload) {
    try {
      //FIXME: Initiate transaction with Payout partner here
      await this.peexService.requestPayment({
        amount,
        track_id: transactionId,
        mobile_phone: receipientPhonenumber,
      });

      const jobName = `initiate-remittance-payout-${transactionId}`;
      this.webhooksQueue.process(jobName, async (_, done) => {
        this.logger.log(
          `Processing (event: ${jobName}, PayoutRef: ${transactionId}...`
        );

        const payment = await this.peexService.getRequestPayment(transactionId);
        if (payment?.status === 'failed') {
          await this.sendReceiptEmail(
            transactionId,
            new Date(),
            payment.amount
          );
        } else if (payment?.status === 'paid') {
          await this.sendReceiptEmail(
            transactionId,
            new Date(),
            payment.amount
          );
        } else {
          return done(Error('Payout not completed yet!'));
        }

        done(null, payment);
        this.logger.log(
          `Successfully processed (event: ${jobName}) from server.`
        );
      });
      await this.webhooksQueue.add(jobName, {
        attempts: 3,
        backoff: { type: 'exponential', delay: 15000 },
      });
    } catch (error) {
      this.logger.error(error);
    }
  }
}
