name: CD

on:
  push:
    branches:
      - '**'

permissions:
  contents: read # Allows reading repository content
  packages: write # Allows publishing packages to GHCR

jobs:
  customer-web:
    runs-on: ubuntu-22.04

    steps:
      - name: List Repository Files
        run: ls -la # Your repo files are already here!

      - name: Checkout customer-web
        uses: ./.github/actions/checkout

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.app
          push: true
          tags: |
            ghcr.io/${{ github.repository }}_fe:latest
            ghcr.io/${{ github.repository }}_fe:${{ github.run_number }}

      - name: Deploy on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: . ./deploy.sh

  wallet-api:
    runs-on: ubuntu-22.04

    steps:
      - name: List Repository Files
        run: ls -la # Your repo files are already here!

      - name: Checkout wallet-api
        uses: ./.github/actions/checkout

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ghcr.io/${{ github.repository }}_api:latest
            ghcr.io/${{ github.repository }}_api:${{ github.run_number }}

      - name: Deploy on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: . ./deploy.sh
