name: CD

on:
  pull_request:
    branches:
      - master
      - release/v**

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # Allows reading repository content
      packages: write # Allows publishing packages to GHCR
    strategy:
      matrix:
        service:
          - {
              name: customer-web,
              dockerfile: Dockerfile.app,
              image_suffix: _fe,
            }
          - { name: wallet-api, dockerfile: Dockerfile.api, image_suffix: _api }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & Publish ${{ matrix.service.name }}
        uses: ./.github/actions/build
        with:
          publish: ${{ github.ref == 'refs/heads/master' }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ${{ matrix.service.dockerfile }}
          docker-image-tags: |
            ghcr.io/${{ github.repository }}${{ matrix.service.image_suffix }}:latest
            ghcr.io/${{ github.repository }}${{ matrix.service.image_suffix }}:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read # Allows reading repository content
      packages: read # Allows pull packages from GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              mkdir -p /home/${{ github.repository }} & cd /home/${{ github.repository }}

              echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
              docker compose pull
              docker compose up -d --remove-orphans
